[2024-07-22T18:27:23.829+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T18:27:23.849+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: enrich_prod.cleaning.check_bdd_sensor scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2024-07-22T18:27:23.855+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: enrich_prod.cleaning.check_bdd_sensor scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2024-07-22T18:27:23.855+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T18:27:23.864+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): cleaning.check_bdd_sensor> on 2023-12-02 00:00:00+00:00
[2024-07-22T18:27:23.873+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2519) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T18:27:23.874+0000] {standard_task_runner.py:64} INFO - Started process 2521 to run task
[2024-07-22T18:27:23.874+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'enrich_prod', 'cleaning.check_bdd_sensor', 'scheduled__2023-12-02T00:00:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/enrich.py', '--cfg-path', '/tmp/tmp9qw3u89k']
[2024-07-22T18:27:23.875+0000] {standard_task_runner.py:91} INFO - Job 218: Subtask cleaning.check_bdd_sensor
[2024-07-22T18:27:23.911+0000] {task_command.py:426} INFO - Running <TaskInstance: enrich_prod.cleaning.check_bdd_sensor scheduled__2023-12-02T00:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T18:27:23.982+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='enrich_prod' AIRFLOW_CTX_TASK_ID='cleaning.check_bdd_sensor' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T00:00:00+00:00'
[2024-07-22T18:27:23.983+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T18:27:23.992+0000] {python.py:75} INFO - Poking callable: <function check_file at 0x7286307c4220>
[2024-07-22T18:27:44.070+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-07-22T18:27:44.071+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T18:27:44.073+0000] {process_utils.py:132} INFO - Sending 15 to group 2521. PIDs of all processes in the group: [2521]
[2024-07-22T18:27:44.073+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2521
[2024-07-22T18:27:44.074+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-22T18:27:44.074+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T18:27:44.082+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-22T18:27:44.085+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=enrich_prod, task_id=cleaning.check_bdd_sensor, run_id=scheduled__2023-12-02T00:00:00+00:00, execution_date=20231202T000000, start_date=20240722T182723, end_date=20240722T182744
[2024-07-22T18:27:44.125+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2521, status='terminated', exitcode=2, started='18:27:22') (2521) terminated with exit code 2
