[2024-07-22T16:40:01.715+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:40:02.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-10T06:00:00+00:00 [queued]>
[2024-07-22T16:40:02.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-10T06:00:00+00:00 [queued]>
[2024-07-22T16:40:02.018+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:40:02.027+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): sensor_congestion> on 2024-07-10 06:00:00+00:00
[2024-07-22T16:40:02.036+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=571) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:40:02.038+0000] {standard_task_runner.py:64} INFO - Started process 577 to run task
[2024-07-22T16:40:02.038+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'sensor_congestion', 'scheduled__2024-07-10T06:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmp8l5m64ms']
[2024-07-22T16:40:02.040+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask sensor_congestion
[2024-07-22T16:40:02.078+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-10T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:40:02.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='sensor_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-10T06:00:00+00:00'
[2024-07-22T16:40:02.156+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:40:02.167+0000] {python.py:75} INFO - Poking callable: <function check_data_in_table at 0x72864ff79800>
[2024-07-22T16:40:02.171+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T16:40:02.171+0000] {extract.py:128} INFO - where date is 2024-07-09
[2024-07-22T16:40:02.171+0000] {extract.py:99} INFO - get data to date 28 and year 2024
[2024-07-22T16:40:02.176+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T16:55:34.343+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-07-22T16:55:34.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T16:55:34.345+0000] {process_utils.py:132} INFO - Sending 15 to group 577. PIDs of all processes in the group: [577]
[2024-07-22T16:55:34.346+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 577
[2024-07-22T16:55:34.346+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-22T16:55:34.346+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T16:55:34.356+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-22T16:55:34.359+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=motower_daily_prod, task_id=sensor_congestion, run_id=scheduled__2024-07-10T06:00:00+00:00, execution_date=20240710T060000, start_date=20240722T164002, end_date=20240722T165534
[2024-07-22T16:55:34.398+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=577, status='terminated', exitcode=2, started='16:40:01') (577) terminated with exit code 2
