[2024-07-22T18:20:23.036+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T18:20:23.061+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: enrich_prod.cleaning.check_ihs_sensor scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-07-22T18:20:23.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: enrich_prod.cleaning.check_ihs_sensor scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-07-22T18:20:23.070+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T18:20:23.084+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): cleaning.check_ihs_sensor> on 2023-10-02 00:00:00+00:00
[2024-07-22T18:20:23.096+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2401) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T18:20:23.098+0000] {standard_task_runner.py:64} INFO - Started process 2416 to run task
[2024-07-22T18:20:23.098+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'enrich_prod', 'cleaning.check_ihs_sensor', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/enrich.py', '--cfg-path', '/tmp/tmpzeq1mddg']
[2024-07-22T18:20:23.100+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask cleaning.check_ihs_sensor
[2024-07-22T18:20:23.142+0000] {task_command.py:426} INFO - Running <TaskInstance: enrich_prod.cleaning.check_ihs_sensor scheduled__2023-10-02T00:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T18:20:23.229+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='enrich_prod' AIRFLOW_CTX_TASK_ID='cleaning.check_ihs_sensor' AIRFLOW_CTX_EXECUTION_DATE='2023-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-02T00:00:00+00:00'
[2024-07-22T18:20:23.230+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T18:20:23.244+0000] {python.py:75} INFO - Poking callable: <function check_file at 0x7286307a0220>
[2024-07-22T18:27:21.836+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-07-22T18:27:21.837+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T18:27:21.839+0000] {process_utils.py:132} INFO - Sending 15 to group 2416. PIDs of all processes in the group: [2416]
[2024-07-22T18:27:21.839+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2416
[2024-07-22T18:27:21.839+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-22T18:27:21.840+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T18:27:21.849+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-22T18:27:21.853+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=enrich_prod, task_id=cleaning.check_ihs_sensor, run_id=scheduled__2023-10-02T00:00:00+00:00, execution_date=20231002T000000, start_date=20240722T182023, end_date=20240722T182721
[2024-07-22T18:27:21.891+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2416, status='terminated', exitcode=2, started='18:20:22') (2416) terminated with exit code 2
